### ISSUE TITLE
Wrong roots for a particular set of coefficients

### ISSUE THREAD

**Issue by paulromano** [cridemichel/QUARTICPP#1]
I've run into an interesting case where this solver returns incorrect roots. The quartic equation I'm solving is:
```
x^4 + (2.2459773428819827)*x^3 + (-14.480985471938862)*x^2 + (-17.678187643398402)*x + 1.0 = 0.0
```
It is clear if you [plot this function](https://www.desmos.com/calculator/hdmapemkon) that it has four real roots, one of which is close to zero. However, if I use these coefficients in quarticpp:
```diff
diff --git a/quartic.cpp b/quartic.cpp
index 8419df5..2d09a0c 100644
--- a/quartic.cpp
+++ b/quartic.cpp
@@ -6,7 +6,7 @@ int main(void)
   pvector<complex<double>,-1> r(4);
   // This is the Case 2 among accuracy tests in ACM Trans. Math. Softw. 46, 2, Article 20 (May 2020),
   // https://doi.org/10.1145/3386241
-  c << 16.048044012,-32.072044006,24.036011,-8.006,1.0; 
+  c << 1.0,-17.678187643398402,-14.480985471938862,2.2459773428819827,1.0;
   Q.set_coeff(c);
 
   Q.find_roots(r);
```
I get the following result:
```
root #0=(2.299680318701711,-1.98613863196097e-08)
p(#0)=(-60.9533417423429,5.293955920339377e-22)

root #1=(2.299680318701711,1.98613863196097e-08)
p(#1)=(-60.9533417423429,-5.293955920339377e-22)

root #2=(-3.422668990142702,-2.956017430098731e-08)
p(#2)=(-60.95334174234289,2.117582368135751e-22)

root #3=(-3.422668990142702,2.956017430098731e-08)
p(#3)=(-60.95334174234289,-2.117582368135751e-22)
```
That is, it returns four complex roots and when it evaluates the polynomial at those roots, it gets a value far from zero. Any idea why this might be happening? Interestingly, if I perturb the coefficient on the x^3 term ever so slightly (for example, 2.2459773428819857), it returns the correct roots.

**Comment by cridemichel** [comment]
Dear Paul,
thank you for reporting this issue. I discovered that I used a slightly too stringent condition which triggered the problem that you reported. Now, it has been fixed, 
best regards
Cristiano

**Comment by paulromano** [comment]
@cridemichel Thanks so much for your quick response and fix! Everything is working great now :+1:

**Comment by cridemichel** [comment]
thank you!

Cristiano De Michele
***@***.***
